// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKJh4SkDWwtd_JjLKSGsvY9HZM_jzNu4w',
    appId: '1:248999239085:web:a84451c29e2caed9b89524',
    messagingSenderId: '248999239085',
    projectId: 'csp-project-c3977',
    authDomain: 'csp-project-c3977.firebaseapp.com',
    storageBucket: 'csp-project-c3977.firebasestorage.app',
    measurementId: 'G-VJ0RV3BZBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATKEuOdvONKRi40X7IlGjm98EN21y3k9g',
    appId: '1:248999239085:android:3a048d3f3a1debdab89524',
    messagingSenderId: '248999239085',
    projectId: 'csp-project-c3977',
    storageBucket: 'csp-project-c3977.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArq7FZ6xDEXoqeEussW5QaldYo5CASiaY',
    appId: '1:248999239085:ios:ae724e2bbd754129b89524',
    messagingSenderId: '248999239085',
    projectId: 'csp-project-c3977',
    storageBucket: 'csp-project-c3977.firebasestorage.app',
    iosClientId: '248999239085-c9i93ipspu634h4hgkmdkoj39ke0fung.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectCsp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArq7FZ6xDEXoqeEussW5QaldYo5CASiaY',
    appId: '1:248999239085:ios:ae724e2bbd754129b89524',
    messagingSenderId: '248999239085',
    projectId: 'csp-project-c3977',
    storageBucket: 'csp-project-c3977.firebasestorage.app',
    iosClientId: '248999239085-c9i93ipspu634h4hgkmdkoj39ke0fung.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectCsp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKJh4SkDWwtd_JjLKSGsvY9HZM_jzNu4w',
    appId: '1:248999239085:web:a312a272fccf8cf5b89524',
    messagingSenderId: '248999239085',
    projectId: 'csp-project-c3977',
    authDomain: 'csp-project-c3977.firebaseapp.com',
    storageBucket: 'csp-project-c3977.firebasestorage.app',
    measurementId: 'G-M2K53CXM6G',
  );

}